---
name: Games-Tournament-Swiss
version: 0.09
author:
  - 'Dr Bean <drbean, followed by the at mark (@), cpan, then a dot, and finally, org>'
abstract: FIDE Swiss Same-Rank Contestant Pairing
license: perl
requires:
  List::MoreUtils: 0
recommends:
  IO::All: 0
  Parse::RecDescent: 0
  YAML: 0
build_requires:
  IO::All: 0
  Parse::RecDescent: 0
  Test::More: 0
  YAML: 0
provides:
  Games::Tournament:
    file: lib/Games/Tournament.pm
    version: 0.01
  Games::Tournament::Card:
    file: lib/Games/Tournament/Card.pm
    version: 0.01
  Games::Tournament::Contestant:
    file: lib/Games/Tournament/Contestant.pm
    version: 0.02
  Games::Tournament::Contestant::Swiss:
    file: lib/Games/Tournament/Contestant/Swiss.pm
    version: 0.01
  Games::Tournament::Contestant::Swiss::Preference:
    file: lib/Games/Tournament/Contestant/Swiss/Preference.pm
    version: 0.01
  Games::Tournament::Swiss:
    file: lib/Games/Tournament/Swiss.pm
    version: 0.09
  Games::Tournament::Swiss::Bracket:
    file: lib/Games/Tournament/Swiss/Bracket.pm
    version: 0.01
  Games::Tournament::Swiss::Config:
    file: lib/Games/Tournament/Swiss/Config.pm
    version: 0.02
  Games::Tournament::Swiss::Procedure:
    file: lib/Games/Tournament/Swiss/Procedure.pm
    version: 0.03
  Games::Tournament::Swiss::Procedure::Dummy:
    file: lib/Games/Tournament/Swiss/Procedure/Dummy.pm
    version: 0.01
  Games::Tournament::Swiss::Procedure::FIDE:
    file: lib/Games/Tournament/Swiss/Procedure/FIDE.pm
    version: 0.05
generated_by: Module::Build version 0.2611
